### ISSUE TITLE
Initial testing feedback

### ISSUE THREAD

**Issue by cagrimmett** [a8cteam51/internet-archive-wayback-machine-link-fixer#29]
First, thank you for all of your work on this, @gin0115! I know I didn't give a lot of direction, but you came up with a solid plugin.

## General
1. @tommusrhodus already shared the feedback about the different approach for updating the link fixing (instead of checking old versions of the particular page and comparing the link content, query the wayback API for the broken link itself and replace with archived version)
2. Let's make this feel more native WordPress-y. Instead of custom lists and filtering, use things like the standard Post list table, styles, and filtering.
3. I don't think this needs a top-level sidebar menu item. It can live under Tools.
4. There should be an overview page for the plugin. Designs/content forthcoming.

## All Reports page
- Use the standard Post list table, styles, and filtering for the reports table. Little actions section like WooCommerce.
- Add a button to the top to create a new report

## Report Detail page
- Use the standard Post list table, styles, and filtering for the report details
- Add filtering: User should be able to filter by status code here. Mostly interested in just broken links. 
- Perhaps there should be another level of detail... A two column list for each post with the X links found and the Y broken ones, or a single list with the broken ones highlighted in a different color.
- The user should be able to take action on the broken links from the report detail page. Say, perhaps, that the report did not include the fixing option, and it highlighted broken ones. Then the user would want to fix the broken ones from the Report Detail page. The workflow would be something like: Filter to broken links, have them all pre-checked (user can uncheck ones they want to skip), and a button that allows you to do the replacement from the report screen.

## New Report page
- Instead of a comma separated list, the status codes should probably be a multi-select or a checklist.
- Defaults should be 404, 500, 502. 
- Remove the single post opt-put, but instead put a custom filter option for developers. It could use wp_query and allow the developer to pass in a query of items to SKIP.

**Comment by gin0115** [comment]
Hey

Been working on the new flow and ive hit a slight snag. The way it is working is as follows.

We find a broken link, we add `wlf-archived` class to the orginal link and then we add a new link with the class `wlf-archived__redirect` afterwards. This works fine for links within paragraph blocks

WAS
```html
<a href="https://glynns-singing-dancing-jetpack.mystagingwebsite.com/2024/02/05/page-that-is-removed-2/">Link 2</a>
````
NOW
````html
<a class="wlf-archived" href="https://glynns-singing-dancing-jetpack.mystagingwebsite.com/2024/02/05/page-that-is-removed-2/">Link 2</a>
<a href="http://web.archive.org/web/20240205110104/https://glynns-singing-dancing-jetpack.mystagingwebsite.com/2024/02/05/page-that-is-removed-2/" class="wlf-archived__redirect">Archived Link</a>
````
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/ec32b9ed-aa30-4b64-8702-c2d48fa2e984)
> Obviously no styles added

BUT i have an issue when it comes to a Button Block

WAS

````html
<div class="wp-block-buttons is-layout-flex wp-block-buttons-is-layout-flex">
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button" href="https://glynns-singing-dancing-jetpack.mystagingwebsite.com/2024/02/05/page-that-is-removed-2/">Link 2</a></div>
</div>
````
NOW

````html
<div class="wp-block-buttons is-layout-flex wp-block-buttons-is-layout-flex">
<div class="wp-block-button"><a class="wp-block-button__link wp-element-button wlf-archived" href="https://glynns-singing-dancing-jetpack.mystagingwebsite.com/2024/02/05/page-that-is-removed-2/">Link 2</a><a href="http://web.archive.org/web/20240205110104/https://glynns-singing-dancing-jetpack.mystagingwebsite.com/2024/02/05/page-that-is-removed-2/" class="wlf-archived__redirect">Archived Link</a></div>
</div>
````

Because a button block can only have 1 link, it shows up as broken content
![image](https://github.com/a8cteam51/wayback-link-fixer/assets/28779094/13a2f68d-c436-4de2-86c9-add811017765)

Fixing it, reverses the changes

Im looking at another possible solution..

**Comment by tommusrhodus** [comment]
@gin0115 How about extending the button block to include an `archivedHref` attribute that you then write to as storage.

**Comment by gin0115** [comment]
@tommusrhodus as mentioned on Slack, React also clears any `data-` attributes added to the button.

I could add an additional field to the button block to allow the archived url link to be retained, BUT we could have other blocks on sites that compile `<a>` tags and have the same issue. 

Not sure if we are best just updating the URL and adding a class, which we can then use JS on to how a tool tip when you hover over to say archived link 🤷🏼‍♂️

**Comment by gin0115** [comment]
Another solution is we 
1. Update the links with the new URL and set a class to denote it being archived
2. Create an array in post meta of all the changes

````php
[['was' => 'old.com', 'now' => 'archived.com/old.com'],....]
````
That way we have a record and we could do some custom JS that uses AJAX/REST to get the old urls from DB to show if we wanted to
